// exemplo de importação de ícones da biblioteca Hugeicons

import { HugeiconsIcon as BaseHugeiconsIcon } from "@hugeicons/react";

import {
  SaveMoneyDollarIcon,
  SaveIcon,
  WavingHand02Icon,
  Home01Icon,
  Wallet01Icon,
  Settings01Icon,
  TradeUpIcon,
  CheckIcon,
  Sun03Icon,
  Moon02Icon,
  Search01Icon,
  Notification01Icon,
  Chart01Icon,
  Target01Icon,
  Home07Icon,
  MultiplicationSignIcon,
  InformationCircleIcon,
  Tick01Icon,
  Upload01Icon,
  ArrowDownBigIcon,
  ArrowDown04Icon,
  ArrowLeft01Icon,
  ArrowUpBigIcon,
  ArrowUp04Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Calendar03Icon,
  Menu01Icon,
  PlusIcon,
  Call02Icon,
  Mail01Icon,
  Logout05Icon,
  Delete02Icon,
  ConstructionIcon,
  Plant01Icon,
  ArrowRight01Icon,
  ArrowLeftDoubleIcon,
  ArrowRightDoubleIcon,
  PanelRightOpenIcon,
  SecurityIcon,
  SquareLock02Icon,
  EyeOffIcon,
  ViewIcon,
  UserGroupIcon,
  UserAdd01Icon,
  Clock01Icon,
  Edit02Icon,
  UserBlock01Icon,
  UserCheck01Icon,
  ContactBookIcon,
  UnavailableIcon,
  Undo03Icon,
  RealEstate01Icon
} from "@hugeicons/core-free-icons";

function HugeiconsIcon({ className = "", ...props }) {
  const classNames = ["hugeicons-icon", className].filter(Boolean).join(" ");

  return <BaseHugeiconsIcon {...props} className={classNames} />;
}

export {
  HugeiconsIcon,
  SaveMoneyDollarIcon,
  SaveIcon,
  WavingHand02Icon,
  Home01Icon,
  Wallet01Icon,
  Settings01Icon,
  TradeUpIcon,
  CheckIcon,
  Sun03Icon,
  Moon02Icon,
  Search01Icon,
  Notification01Icon,
  Chart01Icon,
  Target01Icon,
  Home07Icon,
  ArrowLeft01Icon,
  MultiplicationSignIcon,
  InformationCircleIcon,
  Tick01Icon,
  Upload01Icon,
  ArrowDownBigIcon,
  ArrowDown04Icon,
  ArrowUpBigIcon,
  ArrowUp04Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  Calendar03Icon,
  Menu01Icon,
  PlusIcon,
  Call02Icon,
  Mail01Icon,
  Logout05Icon,
  Delete02Icon,
  ConstructionIcon,
  Plant01Icon,
  ArrowRight01Icon,
  ArrowLeftDoubleIcon,
  ArrowRightDoubleIcon,
  PanelRightOpenIcon,
  SecurityIcon,
  SquareLock02Icon,
  EyeOffIcon,
  ViewIcon,
  UserGroupIcon,
  UserAdd01Icon,
  Clock01Icon,
  Edit02Icon,
  UserBlock01Icon,
  UserCheck01Icon,
  ContactBookIcon,
  UnavailableIcon,
  Undo03Icon,
  RealEstate01Icon
};