// exemplo de importação de ícones da biblioteca Hugeicons

import { HugeiconsIcon } from "@hugeicons/react";

import {
  SaveMoneyDollarIcon,
  WavingHand02Icon,
  Home01Icon,
  Wallet01Icon,
  Settings01Icon,
  TradeUpIcon,
  CheckIcon,
  Sun03Icon,
  Moon02Icon,
  Search01Icon,
  Notification01Icon,
  Chart01Icon,
  Target01Icon,
  Home07Icon,
  MultiplicationSignIcon,
  InformationCircleIcon,
  Tick01Icon,
  Upload01Icon,
  ArrowDownBigIcon,
  ArrowDown04Icon,
  ArrowLeft01Icon,
  ArrowUpBigIcon,
  ArrowUp04Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Calendar03Icon,
  Menu01Icon,
  PlusIcon,
  Call02Icon,
  Mail01Icon,
  Logout05Icon,
  Delete02Icon,
  ConstructionIcon,
  Plant01Icon,
  ArrowRight01Icon,
  ArrowLeftDoubleIcon,
  ArrowRightDoubleIcon,
} from "@hugeicons/core-free-icons";

export {
  HugeiconsIcon,
  SaveMoneyDollarIcon,
  WavingHand02Icon,
  Home01Icon,
  Wallet01Icon,
  Settings01Icon,
  TradeUpIcon,
  CheckIcon,
  Sun03Icon,
  Moon02Icon,
  Search01Icon,
  Notification01Icon,
  Chart01Icon,
  Target01Icon,
  Home07Icon,
  ArrowLeft01Icon,
  MultiplicationSignIcon,
  InformationCircleIcon,
  Tick01Icon,
  Upload01Icon,
  ArrowDownBigIcon,
  ArrowDown04Icon,
  ArrowUpBigIcon,
  ArrowUp04Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  Calendar03Icon,
  Menu01Icon,
  PlusIcon,
  Call02Icon,
  Mail01Icon,
  Logout05Icon,
  Delete02Icon,
  ConstructionIcon,
  Plant01Icon,
  ArrowRight01Icon,
  ArrowLeftDoubleIcon,
  ArrowRightDoubleIcon,
};
