function getCurrentMonthDate(daysAgo) {
    const today = new Date();
    const day = Math.max(1, today.getDate() - daysAgo);
    const month = String(today.getMonth() + 1).padStart(2, "0");

    return `${today.getFullYear()}-${month}-${String(day).padStart(2, "0")}`;
}

export const MOCK_TRANSACTIONS = [
    {
        id: 1,
        descricao: "Aluguel Apartamento",
        categoria: "moradia",
        categoriaLabel: "Moradia",
        data: getCurrentMonthDate(1),
        metodo: "Débito Automático",
        conta: "Nubank",
        valor: 2100,
        tipo: "despesa",
    },
    {
        id: 2,
        descricao: "Mercado Extra",
        categoria: "alimentacao",
        categoriaLabel: "Alimentação",
        data: getCurrentMonthDate(2),
        metodo: "Cartão Crédito",
        conta: "Nubank",
        valor: 420,
        tipo: "despesa",
    },
    {
        id: 3,
        descricao: "Netflix + Spotify",
        categoria: "entretenimento",
        categoriaLabel: "Entretenimento",
        data: getCurrentMonthDate(4),
        metodo: "Cartão Crédito",
        conta: "Inter",
        valor: 89,
        tipo: "despesa",
    },
    {
        id: 4,
        descricao: "Academia SmartFit",
        categoria: "saude",
        categoriaLabel: "Saúde",
        data: getCurrentMonthDate(5),
        metodo: "Débito Automático",
        conta: "Nubank",
        valor: 119,
        tipo: "despesa",
    },
    {
        id: 5,
        descricao: "Uber - Corridas",
        categoria: "transporte",
        categoriaLabel: "Transporte",
        data: getCurrentMonthDate(6),
        metodo: "App",
        conta: "Nubank",
        valor: 156,
        tipo: "despesa",
    },
    {
        id: 6,
        descricao: "Salário - Empresa XYZ",
        categoria: "receita",
        categoriaLabel: "Receita",
        data: getCurrentMonthDate(0),
        metodo: "Transferência",
        conta: "Nubank",
        valor: 8500,
        tipo: "receita",
    },
    {
        id: 7,
        descricao: "Freelance - Design",
        categoria: "receita",
        categoriaLabel: "Receita",
        data: getCurrentMonthDate(3),
        metodo: "PIX",
        conta: "Inter",
        valor: 1800,
        tipo: "receita",
    },
    {
        id: 8,
        descricao: "Rendimento CDB",
        categoria: "investimento",
        categoriaLabel: "Investimento",
        data: getCurrentMonthDate(7),
        metodo: "Automático",
        conta: "Inter",
        valor: 312,
        tipo: "receita",
    },
    {
        id: 9,
        descricao: "Dividendos FII HGLG",
        categoria: "investimento",
        categoriaLabel: "Investimento",
        data: getCurrentMonthDate(8),
        metodo: "Automático",
        conta: "Inter",
        valor: 248,
        tipo: "receita",
    },
];
